#!/usr/bin/env bash
# Prepares everything the sibling `docker-compose.yaml` interpolates:
#
#   * picks and downloads a chain snapshot into ./snapshots,
#   * pins both container images to an immutable `date-digest` tag,
#   * writes the resulting variables to ./.env, which `docker compose` reads
#     automatically from the project directory.
#
# Usage:
#
#   ./prepare.sh [FOREST_IMAGE_TAG]
#   docker compose up --abort-on-container-exit --exit-code-from rpc-checks
#
# FOREST_IMAGE_TAG is a `date-digest` tag such as `2026-08-10-0b42ef6`. If not
# set then will use the `date-digest` for the current HEAD.
#
# Knobs, all optional:
#
#   CHAIN     network to test, defaults to calibnet
#   DAYS_AGO  age of the snapshot to fetch, defaults to 2
#   EPOCHS    how many epochs to back-fill and check, defaults to 1000

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
SNAPSHOT_DIR="$SCRIPT_DIR/snapshots"
ENV_FILE="$SCRIPT_DIR/.env"

CHAIN="${CHAIN:-calibnet}"
DAYS_AGO="${DAYS_AGO:-2}"
EPOCHS="${EPOCHS:-1000}"

ARCHIVE_URL="https://forest-archive.chainsafe.dev/list/$CHAIN/latest-v2?format=json"

fail() {
  echo "$*" >&2
  exit 1
}

is_non_negative_integer() {
  [[ $1 =~ ^[0-9]+$ ]]
}

# Prints the UTC date, `$1` days in the past, as YYYY-MM-DD. GNU and BSD `date`
# spell date arithmetic differently, and only GNU understands `--version`, which
# is what tells the two apart here. CI will be 99% of the time GNU.
utc_day_offset() {
  if date --version >/dev/null 2>&1; then
    date -u -d "$1 days ago" +%F
  else
    date -u -v-"$1"d +%F
  fi
}

# Prints the `date-digest` tag of the image built from the checked out `HEAD`,
# e.g. `2026-08-10-0b42ef6`
forest_tag_for_head() {
  local date short
  date=$(TZ=UTC git -C "$SCRIPT_DIR" show -s --format=%cd --date=format-local:%Y-%m-%d HEAD)
  short=$(git -C "$SCRIPT_DIR" rev-parse --short=7 HEAD)
  echo "$date-$short"
}

forest_image_tag="${1:-$(forest_tag_for_head)}"
[[ $forest_image_tag =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9a-f]{7,}$ ]] ||
  fail "FOREST_IMAGE_TAG must look like 2026-08-10-0b42ef6, got '$forest_image_tag'"

is_non_negative_integer "$DAYS_AGO" || fail "DAYS_AGO must be a non-negative integer, got '$DAYS_AGO'"
is_non_negative_integer "$EPOCHS" || fail "EPOCHS must be a non-negative integer, got '$EPOCHS'"
((EPOCHS >= 1)) || fail "EPOCHS must be at least 1"

# find the most recent snapshot download URL for the $DAYS_AGO argument
day=$(utc_day_offset "$DAYS_AGO")
url=$(curl --silent --show-error --fail --location --connect-timeout 10 --retry 3 --max-time 60 "$ARCHIVE_URL" |
  jq --raw-output --arg day "$day" '[.items[].url | select(contains("_" + $day + "_"))] | first')
[[ -n $url && $url != null ]] || fail "no $CHAIN snapshot published for $day"

file=$(basename "$url")

# Snapshot names carry the epoch of their head tipset, as in
# `forest_snapshot_calibnet_2026-08-10_height_3000000.forest.car.zst`.
# Strip everything up to and including `_height_`, then everything from the first `.`.
head_epoch=${file##*_height_}
head_epoch=${head_epoch%%.*}
is_non_negative_integer "$head_epoch" || fail "could not parse a head epoch out of '$file'"
((EPOCHS <= head_epoch)) || fail "EPOCHS ($EPOCHS) exceeds the snapshot head epoch ($head_epoch)"

mkdir -p "$SNAPSHOT_DIR"
destination="$SNAPSHOT_DIR/$file"

# aria2 is a better option for heavy file downloads
# it keeps a control file next to a download and removes it
# once the transfer finishes, --continue helps for abrupt
# interruptions resuming the download instead of starting over
if [[ -f $destination && ! -f $destination.aria2 ]]; then
  echo "Reusing the snapshot already downloaded at $destination"
else
  aria2c \
    --max-connection-per-server=5 \
    --split=5 \
    --continue=true \
    --auto-file-renaming=false \
    --console-log-level=warn \
    --summary-interval=30 \
    --dir="$SNAPSHOT_DIR" \
    --out="$file" \
    "$url"
fi

forest_image="${FOREST_IMAGE:-ghcr.io/chainsafe/forest:$forest_image_tag}"

# The checks cover the epochs the node has an index for: back-filling N epochs
# from the head leaves the range [head - N, head - 1] queryable.
cat >"$ENV_FILE" <<EOF
# Generated by prepare.sh, do not edit.
CHAIN=$CHAIN
SNAPSHOT=$file
START=$((head_epoch - EPOCHS))
END=$((head_epoch - 1))
BACKFILL=$((EPOCHS + 1))
FOREST_IMAGE=$forest_image
EOF

echo "Wrote $ENV_FILE:"
cat "$ENV_FILE"
