# This Dockerfile is used for consistent build environment in CI
# Example usage:
# docker build -t forest/rust:latest -f ./Dockerfile-ci .
# docker run forest/rust cargo c

FROM rust:1-buster

WORKDIR /usr/src/forest
COPY . .

# Install dependencies
RUN apt-get update
RUN apt-get install --no-install-recommends -y build-essential clang ocl-icd-opencl-dev

RUN bash -l -c 'echo $(rustc --print sysroot)/lib >> /etc/ld.so.conf'
RUN bash -l -c 'echo /usr/local/lib >> /etc/ld.so.conf'
RUN ldconfig
