# This Dockerfile is for the main forest binary
# 
# Build and run locally:
# ```
# docker build -t forest:alpine -f ./Dockerfile-alpine .
# docker run --init -it forest:alpine
# ```
# 
# Build and manually push to Github Container Registry (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
# ```
# docker build -t ghcr.io/chainsafe/forest:alpine .
# docker push ghcr.io/chainsafe/forest:alpine
# ```

##
# Build stage
# Use github action runner cached images to avoid being rate limited
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#cached-docker-images
## 
FROM alpine AS build-env

# Install dependencies
RUN apk update
RUN apk add git curl protobuf make cmake gcc clang clang-dev musl-dev opencl-icd-loader-dev
RUN update-ca-certificates

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /forest
COPY . .

# Install Forest. Move it out of the cache for the prod image.
RUN --mount=type=cache,sharing=private,target=/root/.cargo/registry \
    --mount=type=cache,sharing=private,target=/root/.rustup \
    --mount=type=cache,sharing=private,target=/forest/target \
    make install-with-mimalloc && \
    mkdir /forest_out && \
    cp /root/.cargo/bin/forest* /forest_out

##
# Prod image for forest binary
# Use github action runner cached images to avoid being rate limited
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#cached-docker-images
##
FROM alpine

# Link package to the repository
LABEL org.opencontainers.image.source https://github.com/chainsafe/forest
ARG SERVICE_USER=forest
ARG SERVICE_GROUP=forest

# Install binary dependencies
RUN apk update
RUN apk add aria2 ca-certificates opencl-icd-loader
RUN update-ca-certificates

# Create user and group and assign appropriate rights to the forest binaries
RUN addgroup --gid 1000 ${SERVICE_GROUP} && adduser --uid 1000 --ingroup ${SERVICE_GROUP} --disabled-password --gecos "" ${SERVICE_USER}

# Copy forest daemon and cli binaries from the build-env
COPY --from=build-env --chown=${SERVICE_USER}:${SERVICE_GROUP} /forest_out/* /usr/local/bin/

USER ${SERVICE_USER}
WORKDIR /home/${SERVICE_USER}

ENTRYPOINT ["forest"]
