{
 "title": "forest",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head Epoch",
   "type": "stat",
   "description": "Latest epoch synchronized to the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_epoch{}" }
   ]
  },
  {
   "title": "Tipsets Validated per Minute",
   "type": "stat",
   "description": "Number of Tipset Validated Per min in the last 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(head_epoch{}[60m]) * 60", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Network Height Diff",
   "type": "timeseries",
   "description": "The difference between the node's network height and the expected network height.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "expected_network_height{} - head_epoch{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Wall Time",
   "type": "stat",
   "description": "Time since the Forest Node process started",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{}) / 60 / 60"
    }
   ]
  },
  {
   "title": "Full Peers",
   "type": "timeseries",
   "description": "Number of healthy peers recognized by the Forest node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "full_peers{}" }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "description": "The Forest Process Resident memory size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{} / 1073741824"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bad Peers",
   "type": "timeseries",
   "description": "Number of bad peers recognized by the node.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 26 },
   "targets": [
    { "expr": "bad_peers{}" }
   ]
  },
  {
   "title": "Peer Connected P2P Events",
   "type": "timeseries",
   "description": "Total count of peer connection events recognized by the Forest Node.",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 26 },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"peer_connected\"}"
    }
   ]
  },
  {
   "title": "Message P2P Events",
   "type": "timeseries",
   "description": "Number of Total count of libp2p PubSub message events  recognized by the Forest Node.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 26 },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"pubsub_message_message\"}"
    }
   ]
  },
  {
   "title": "Peer Disconnected P2P Events",
   "type": "timeseries",
   "description": "Total count of peer disconnection events recognized by the Forest Node.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"peer_disconnected\"}"
    }
   ]
  },
  {
   "title": "Failed Peer Requests",
   "type": "timeseries",
   "description": "Number of Failed Peer Requests recognized by the Forest node.",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 32 },
   "targets": [
    { "expr": "peer_failure_total_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block P2P Events",
   "type": "timeseries",
   "description": "Total count of peer disconnection events recognized by the Forest Node.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "libp2p_messsage_total_total{libp2p_message_kind=\"peer_disconnected\"}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Size of Forest Node database",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forest_db_size{} /  1073741824 "
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds{}" }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{} / 1073741824"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "stat",
   "description": "Total user and system CPU time spent.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{} / 60 / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Range Sync Failure Count",
   "type": "timeseries",
   "description": "Total count of tipset range synchronization failures encountered by the Forest node",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "tipset_range_sync_failure_total_total{}"
    }
   ]
  }
 ]
}