{
 "title": "forest",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Head Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_epoch{}" }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forest_db_size{} /  1073741824 "
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{} / 60 / 60"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds{}" }
   ]
  },
  {
   "title": "Process Wall Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds) / 60 / 60"
    }
   ]
  },
  {
   "title": "Healthy Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "full_peers{}" }
   ]
  },
  {
   "title": "Bad Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "bad_peers{}" }
   ]
  },
  {
   "title": "Failed Peer Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "peer_failure_total{}" }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{} / 1073741824"
    }
   ]
  },
  {
   "title": "Process Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{} / 1073741824"
    }
   ]
  },
  {
   "title": "LibP2P Message Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "libp2p_messsage_total{}" }
   ]
  },
  {
   "title": "Range Sync Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "tipset_range_sync_failure_total{}"
    }
   ]
  }
 ]
}