FROM ubuntu:22.10

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update
RUN apt-get install -y s3fs ca-certificates curl gnupg lsb-release docker-compose

COPY daily_snapshot/upload_snapshot.sh daily_snapshot/run_service.sh daily_snapshot/docker-compose.yml ./
COPY ruby_common ruby_common
RUN chmod +x run_service.sh
ENTRYPOINT /run_service.sh

