name: Docs Check

# Cancel workflow if there is a new change to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "docs/**"
      - ".config/forest.dic"
      - ".config/spellcheck.toml"
      - ".github/workflows/docs-check.yml"
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
      - "docs/**"
      - ".config/forest.dic"
      - ".config/spellcheck.toml"
      - ".github/workflows/docs-check.yml"

jobs:
  docs-check:
    name: Check
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - name: Check spellcheck dictionary format
        working-directory: .
        run: mise run format-spellcheck-dictionary-check
      - name: Install cargo-spellcheck
        working-directory: .
        run: |
          sudo apt-get install -y libclang-dev
          cargo binstall --no-confirm cargo-spellcheck@0.15.7
      - name: Spellcheck Markdown files
        working-directory: .
        run: mise run lint:spellcheck-markdown
      - run: mise run docs:lint
      - run: mise run docs:build
