name: Unit tests
permissions:
  contents: read

# Cancel workflow if there is a new change to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
    # This needs to be declared explicitly so that the job is actually
    # run when moved out of draft.
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs-*.yml"
      - "**/*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs-*.yml"
      - "**/*.md"

env:
  CI: 1
  CACHE_TIMEOUT_MINUTES: 5
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  RUSTC_WRAPPER: "sccache"
  CC: "sccache clang"
  CXX: "sccache clang++"
  # To minimize compile times: https://nnethercote.github.io/perf-book/build-configuration.html#minimizing-compile-times
  RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=lld"
  FIL_PROOFS_PARAMETER_CACHE: /var/tmp/filecoin-proof-parameters
  RUST_LOG: error
  FOREST_ACTOR_BUNDLE_PATH: /var/tmp/forest_actor_bundle.car.zst

jobs:
  tests-release:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 45
    # Run the job only if the PR is not a draft.
    # This is done to limit the runner cost.
    if: github.event.pull_request.draft == false
    steps:
      - name: Configure SCCache variables
        run: |
          # External PRs do not have access to 'vars' or 'secrets'.
          if [[ "${{secrets.AWS_ACCESS_KEY_ID}}" != "" ]]; then
            echo "SCCACHE_ENDPOINT=${{ vars.SCCACHE_ENDPOINT}}" >> $GITHUB_ENV
            echo "SCCACHE_BUCKET=${{ vars.SCCACHE_BUCKET}}" >> $GITHUB_ENV
            echo "SCCACHE_REGION=${{ vars.SCCACHE_REGION}}" >> $GITHUB_ENV
          fi
      - name: Checkout Sources
        uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: ${{ fromJSON(env.CACHE_TIMEOUT_MINUTES) }}
        continue-on-error: true
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.work"
          cache-dependency-path: "**/go.sum"
      - name: install nextest
        uses: taiki-e/install-action@nextest
      - uses: actions/cache@v5
        id: cache-proof-params
        with:
          path: ${{ env.FIL_PROOFS_PARAMETER_CACHE }}
          key: proof-params-keys
      - uses: actions/cache@v5
        id: cache-actor-bundle
        with:
          path: ${{ env.FOREST_ACTOR_BUNDLE_PATH }}
          key: actor-bundle
      - name: Fetch proof params and RPC test snapshots
        run: |
          cargo run --bin forest-dev --no-default-features --profile quick-test -- fetch-test-snapshots --actor-bundle $FOREST_ACTOR_BUNDLE_PATH
          ls -ahl $FIL_PROOFS_PARAMETER_CACHE
      - uses: jdx/mise-action@v4
      - run: |
          mise test
        env:
          FOREST_TEST_SKIP_PROOF_PARAM_CHECK: 1
          # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          CARGO_BUILD_JOBS: 3
      - name: Upload Test Results to CodeCov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: "test_results"
          files: target/nextest/default/junit.xml
          fail_ci_if_error: false
